Get proper build going

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,7 +24,7 @@ jobs:
           - name: Checkout code
             uses: actions/checkout@v4
           - name: First thing
-            run: echo "Run the build" || ./build.sh
+            run: (echo "Run the build" && ./build.sh) || echo "Build failure"
             shell: bash
           - uses: cpp-linter/cpp-linter-action@v2
             id: linter
